In [6]:
import joblib

model = joblib.load("instrument_models/irmas_models/philarmonia_svm.joblib")
scaler = joblib.load("scalers/irmas/irmas_skl_scaler.joblib")
step = 3

In [7]:
import numpy as np
import librosa

audio, sr = librosa.load("wavfiles/sax_1.wav", sr=22050)

X_file = []
for index in range(0, len(audio) - step * sr, step * sr):
    sample = audio[index:index + step * sr]

    chroma_stft = librosa.feature.chroma_stft(y=sample, sr=sr)
    rms = librosa.feature.rms(y=sample)
    spectral_centroids = librosa.feature.spectral_centroid(y=sample, sr=sr)
    spectral_bandwidths = librosa.feature.spectral_bandwidth(y=sample, sr=sr)
    spectral_rolloff = librosa.feature.spectral_rolloff(y=sample, sr=sr)
    zero_crossing_rates = librosa.feature.zero_crossing_rate(y=sample)
    chroma_cens = librosa.feature.chroma_cens(y=sample, sr=sr)
    tempo, _ = librosa.beat.beat_track(y=sample, sr=sr)
    mfccs = librosa.feature.mfcc(y=sample, sr=sr)

    sample_features = []
    sample_features.append(np.mean(chroma_stft))
    sample_features.append(np.var(chroma_stft))
    sample_features.append(np.mean(rms))
    sample_features.append(np.var(rms))
    sample_features.append(np.mean(spectral_centroids))
    sample_features.append(np.var(spectral_centroids))
    sample_features.append(np.mean(spectral_bandwidths))
    sample_features.append(np.var(spectral_bandwidths))
    sample_features.append(np.mean(spectral_rolloff))
    sample_features.append(np.var(spectral_rolloff))
    sample_features.append(np.mean(zero_crossing_rates))
    sample_features.append(np.var(zero_crossing_rates))
    sample_features.append(np.mean(chroma_cens))
    sample_features.append(np.var(chroma_cens))
    sample_features.append(tempo)
    for i, mfcc_column in zip(range(20), mfccs):
        sample_features.append(np.mean(mfcc_column))
        sample_features.append(np.var(mfcc_column))

    X_file.append(sample_features)

print(X_file)


X_file = np.array(X_file)
X_file_irmas = scaler.transform(X_file)

preds = model.predict(X_file_irmas)
print(preds)

[[0.1521798, 0.07455731, 0.04924868, 0.00024468545, 1704.8346926339095, 247266.4543408468, 1451.7213253229256, 160991.73195500424, 3025.497859074519, 799613.2555511929, 0.06964017427884615, 0.00035348769475722456, 0.14506799, 0.062288612, 99.38401442307692, -333.9012, 8703.718, 60.987576, 2357.823, -75.759155, 509.07043, 16.74864, 259.85217, -30.370146, 116.27213, -20.952623, 100.50312, -20.472227, 75.819756, -7.604331, 24.041927, -27.201914, 29.917437, -8.907523, 86.37813, -0.6504025, 45.92792, -0.6932059, 12.757467, -7.347678, 30.191278, -13.140691, 25.12455, -13.337104, 17.691326, -6.3906107, 8.646519, -12.271732, 13.769723, -13.311524, 29.056303, -11.842467, 9.793382, -17.895346, 24.411005], [0.18558197, 0.076147996, 0.042374875, 0.00021737043, 1720.5555819427993, 322554.0979647633, 1418.1867938208152, 174596.2811961664, 2990.547814002404, 915246.38928637, 0.08450646033653846, 0.0012419157338565624, 0.14651425, 0.061866917, 33.99979440789474, -334.57965, 9516.281, 70.629585, 2279.6

In [8]:
model = joblib.load("instrument_models/philarmonia_models/philarmonia_svm.joblib")
scaler = joblib.load("scalers/philarmonia/philarmonia_skl_scaler.joblib")
step = 3

X_file_phil = scaler.transform(X_file)

preds = model.predict(X_file_phil)
print(preds)

[14 14 15 14 14 15]


C:\Proiecte SSD\Licenta\Basic-Fourier-Usage\venv\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [9]:
model = joblib.load("instrument_models/kaggle_models/kaggle_svm.joblib")
scaler = joblib.load("scalers/kaggle/kaggle_skl_scaler.joblib")
step = 3

X_file_kag = scaler.transform(X_file)

preds = model.predict(X_file_kag)
print(preds)

[7 7 9 7 7 2]


C:\Proiecte SSD\Licenta\Basic-Fourier-Usage\venv\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [10]:
model = joblib.load("genre_models/gtzan_models/gtzan_svm.joblib")
scaler = joblib.load("scalers/gtzan/gtzan_skl_scaler.joblib")
step = 3

X_file_gt = scaler.transform(X_file)

preds = model.predict(X_file_gt)
print(preds)

[1 1 1 1 1 1]


C:\Proiecte SSD\Licenta\Basic-Fourier-Usage\venv\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
